### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by sncsoft** [jackghg/OnKey#2]
Please add to the README file the following libraries requirements before the actual build command -

sudo apt install libgtk2.0-dev libxtst-dev -y

.

**Comment by jackghg** [comment]
right! I will, thanks

**Comment by jackghg** [comment]
done, what is -y ?

**Comment by sncsoft** [comment]
from apt-get

-y, --yes, --assume-yes
           Automatic yes to prompts; assume "yes" as answer to all prompts
and run
           non-interactively. If an undesirable situation, such as changing
a held package,
           trying to install a unauthenticated package or removing an
essential package occurs
           then apt-get will abort. Configuration Item:
APT::Get::Assume-Yes.

somehow there is no -y key in the apt documentation, but somehow the -y key
is working with apt the same way as described above. Sorry for the
confusion. Probably, you want to be precise, just replace "apt" with
"apt-get" in your README. :-)

**Comment by jackghg** [comment]
ok thanks, we dont need the -y. I guess i can close this.

**Comment by sncsoft** [comment]
Sure!
